### ISSUE TITLE
Wouldn't it be possible to add an option for repeated channels for yrrh?

### ISSUE THREAD

**Issue by SADNESS81** [hjk789/Userscripts#17]
as It will help discovering new channels and get off some of the load 
like instead of hiding 10 videos from the same channel it will hide the whole channel

**Comment by hjk789** [comment]
It would be possible, but maybe not feasible. YRRH was made from ground up to filter repeated videos. Filtering repeated channels would require a separate logic. So this being implemented would depend a lot on my disposition for that, which hasn't been good.
