### ISSUE TITLE
Do you plan on updating YouTube-Repeated-Recommendations-Hider script anytime soon?

### ISSUE THREAD

**Issue by uugaabuugaa** [hjk789/Userscripts#18]
The script used to work somewhat until the latest youtube home design update that gives a colored background on hovering over a video in home. It's completely broken now. I see that the script wasn't updated within 2 years so I'm not sure if it's abandoned or not. Only found the script a few months earlier. Hopefully you'll come up with a fix for this.
Not sure if completely filtering out videos work or not since I never used that but dimming the watched/multiple recommended videos is broken. The new design hasn't infected my backup gmail or incognito mode but the main account I use is affected. Apparently some other people are also starting to get the design change. The colored background looks like this.
![Screenshot (45)](https://github.com/user-attachments/assets/937c910c-510b-486a-979d-f5ba5dc63eaa)

**Comment by hjk789** [comment]
Very unlikely. When I made this script I used to spend a lot of time in YouTube, and hiding repeated recommendations was crucial to me. But now I only visit YouTube every now and then, so I'm not even using YRRH anymore. To top it all off, I'm not working in opensource projects anymore, so don't expect updates anytime soon.

**Comment by uugaabuugaa** [comment]
That's a bit sad. But I understand. Thanks anyways.
